language: node_js
node_js: node
script:
  - yarn lint
  - yarn build
branches:
  only:
  - master
cache:
  directories:
    - node_modules
after_success:
  - .travis/push.sh
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: docs
 on:
   branch: master
